SET PATH=C:\Keil_v4\ARM\ARMCC\bin\;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Windows Live\Shared;C:\Program Files\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\MATLAB\R2013b\runtime\win32;C:\Program Files\MATLAB\R2013b\bin;C:\Program Files\MATLAB\R2013b\polyspace\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft Visual Studio\Common\Tools\WinNT;C:\Program Files\Microsoft Visual Studio\Common\MSDev98\Bin;C:\Program Files\Microsoft Visual Studio\Common\Tools;C:\Program Files\Microsoft Visual Studio\VC98\bin
SET CPU_TYPE=STM32F405RG
SET CPU_VENDOR=STMicroelectronics
SET UV2_TARGET=STM32_PSINS
SET CPU_CLOCK=0x017D7840
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_it.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\usart.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\mpu9250.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\main.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\mcu_init.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\misc.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_dma.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_exti.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_gpio.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_i2c.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_pwr.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_rcc.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_spi.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_tim.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_usart.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\stm32f4xx_syscfg.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\system_stm32f4xx.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmAsm" --Via "..\output\startup_stm32f4xx._ia"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\kfapp.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmCC" --Via "..\output\psins.__i"
"C:\Keil_v4\ARM\ARMCC\bin\ArmLink" --Via "..\Output\psins.lnp"
